version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: agenda_db2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jadiran
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: agenda_florescer
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: